---
title: "forage_nutritive_value_analysis_script"
author: "Hannah Phillips"
date: "March 23, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = F, message = F, warning = F}
library(readxl) #read data
library(tidyverse) #piping
library(lme4) #lmer
library(lmerTest) # KR ddf
library(MuMIn) #r.squaredGLMM
library(ggplot2) #plots
library(merTools)
library(afex) #CIs
library(dplyr)
library(lsmeans)

dat <- read_excel("biomass_and_quality_data.xlsx") %>%
  mutate_at(vars(Pen, Forage, Paddock), as.factor) %>%
  mutate(Biomass = as.numeric(Biomass))
```

# Create dataset to use for predictions & function
```{r, include = F}
#create data to make predictions from
newDat = data.frame(Day = rep(0:46, 2), 
                    Forage = c(rep("Rye", 47), 
                               rep("Wheat", 47)), 
                    Pen = NA, 
                    Paddock = NA)

#create prediction function
predict.fun <- function(my.lmm) {
  predict(my.lmm, newdata = newDat, re.form = NA) 
}
```

# yield
```{r, message = F}
#model
model = lmer(Biomass ~ poly(Day, 3)*Forage + (1|Pen) + (1|Paddock/Forage), data = within(dat, 
                          Forage <- relevel(Forage, ref = "Rye")))

#diagnostics
plot(model, main = "Residuals vs fitted")
qqnorm(resid(model))
qqline(resid(model))

#regression coefficients 
summary(model, ddf = "Kenward-Roger")
round(confint(model), 3)
anova(model, ddf = "Kenward-Roger")

#random effects
as.data.frame(VarCorr(model))

#R squared
r.squaredGLMM(model)

```

# yield plot
```{r, echo = F}
# Predicted fitted values
newDat.yield = newDat
newDat.yield$fit <- predict.fun(model)

# 95% confidence intervals based on 1000 bootstrap resamples 
newDat.yield <- cbind(newDat.yield, confint(bootMer(model, predict.fun, nsim = 1000, seed = 1), type = "perc"))

boot.ci.yield <- data.frame(bootMer(model, predict.fun, nsim = 1000, seed = 1)) 

min(subset(newDat.yield, Forage == "Rye")$fit)
max(subset(newDat.yield, Forage == "Rye")$fit)
min(subset(newDat.yield, Forage == "Wheat")$fit)
max(subset(newDat.yield, Forage == "Wheat")$fit)


#Difference between rye - wheat on d0
mean(data.frame(boot.ci.yield$X1 - boot.ci.yield$X48)[,1])
quantile(data.frame(boot.ci.yield$X1 - boot.ci.yield$X48)[,1], 0.025)
quantile(data.frame(boot.ci.yield$X1 - boot.ci.yield$X48)[,1], 0.975)

#Difference between rye - wheat on d2
mean(data.frame(boot.ci.yield$X3 - boot.ci.yield$X50)[,1])
quantile(data.frame(boot.ci.yield$X3 - boot.ci.yield$X50)[,1], 0.025)
quantile(data.frame(boot.ci.yield$X3 - boot.ci.yield$X50)[,1], 0.975)

#Difference between rye - wheat on d22
mean(data.frame(boot.ci.yield$X23 - boot.ci.yield$X70)[,1])
quantile(data.frame(boot.ci.yield$X23 - boot.ci.yield$X70)[,1], 0.025)
quantile(data.frame(boot.ci.yield$X23 - boot.ci.yield$X70)[,1], 0.975)

#Difference between wheat - rye on d33
mean(data.frame(boot.ci.yield$X81 - boot.ci.yield$X34)[,1])
quantile(data.frame(boot.ci.yield$X81 - boot.ci.yield$X34)[,1], 0.025)
quantile(data.frame(boot.ci.yield$X81 - boot.ci.yield$X34)[,1], 0.975)

#Difference between wheat - rye on d43
mean(data.frame(boot.ci.yield$X91 - boot.ci.yield$X44)[,1])
quantile(data.frame(boot.ci.yield$X91 - boot.ci.yield$X44)[,1], 0.025)
quantile(data.frame(boot.ci.yield$X91 - boot.ci.yield$X44)[,1], 0.975)

{
  ggplot(data = dat, 
         aes(x = Day, y = Biomass, color = Forage)) + 
  
  geom_point(size = 1.5, 
             show.legend = T,
             position = position_jitter(h = 0.01, w = 0.01),
             alpha = 0.5) +
  
  scale_color_manual(breaks = c("Rye", "Wheat"), 
                     values = c("darkred", "dodgerblue4")) + 
  
  geom_line(data = newDat.yield, 
            aes(x = Day, y = fit, group = Forage), 
            size = 1) +
  
  geom_ribbon(data = subset(newDat.yield, Forage == "Rye"), 
              aes(x = Day, ymin =`2.5 %`, ymax = `97.5 %`),
              fill = "darksalmon", 
              alpha = 0.5, 
              inherit.aes = FALSE) +
  
  geom_ribbon(data = subset(newDat.yield, Forage == "Wheat"), 
              aes(x = Day, ymin = `2.5 %`, ymax = `97.5 %`),
              fill = "lightskyblue1", alpha = 0.5, inherit.aes = FALSE) +
  
  theme_classic() +
    
  labs(x = "Day of grazing period", 
       y = "Biomass yield, Mg of dry matter ha\u207B\u00B9") +  
  
  scale_y_continuous(breaks = seq(0, 6, 1), 
                     limits = c(0, 6), expand = c(0,0)) +
  
  scale_x_continuous(breaks = seq(0, 46, 2), limits = c(-1, 47), expand = c(0,0)) +
  
  theme(axis.title = element_text(size = 14),
        plot.caption = element_text(size = 11, hjust = 0),   
        axis.text = element_text(size = 11, colour = "black"),
        legend.position = c(.1, .9),
        legend.title = element_blank(),
        legend.direction = "vertical",
        legend.text = element_text(size = 11),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 10, l = 0)))
  }
```

# CP
```{r, message = F}
#model
model = lmer(CP ~ Day*Forage + (1|Pen) + (1|Paddock/Forage), data = within(dat, Forage <- relevel(Forage, ref = "Wheat")))

#diagnostics
plot(model, main = "Residuals vs fitted")
qqnorm(resid(model))
qqline(resid(model))

#regression coefficients 
summary(model, ddf = "Kenward-Roger")
round(confint(model), 2)
anova(model, ddf = "Kenward-Roger")

#random effects
as.data.frame(VarCorr(model))

#R squared
r.squaredGLMM(model)
```

# CP plot
```{r, echo = F}
# Predicted fitted values
newDat.CP = newDat
newDat.CP$fit <- predict.fun(model)

# 95% confidence intervals based on 1000 bootstrap resamples 
newDat.CP <- cbind(newDat.CP, confint(bootMer(model, predict.fun, nsim = 1000, seed = 1), type = "perc"))

boot.ci.cp <- data.frame(bootMer(model, predict.fun, nsim = 1000, seed = 1)) 

min(subset(newDat.ndf, Forage == "Rye")$fit)
max(subset(newDat.ndf, Forage == "Rye")$fit)
min(subset(newDat.ndf, Forage == "Wheat")$fit)
max(subset(newDat.ndf, Forage == "Wheat")$fit)


#Difference between rye - wheat on d0
mean(data.frame(boot.ci.ndf$X1 - boot.ci.ndf$X48)[,1])
quantile(data.frame(boot.ci.ndf$X1 - boot.ci.ndf$X48)[,1], 0.025)
quantile(data.frame(boot.ci.ndf$X1 - boot.ci.ndf$X48)[,1], 0.975)

#Difference between rye - wheat on d5
mean(data.frame(boot.ci.ndf$X6 - boot.ci.ndf$X53)[,1])
quantile(data.frame(boot.ci.ndf$X6 - boot.ci.ndf$X53)[,1], 0.025)
quantile(data.frame(boot.ci.ndf$X6 - boot.ci.ndf$X53)[,1], 0.975)

#Difference between rye - wheat on d36
mean(data.frame(boot.ci.ndf$X37 - boot.ci.ndf$X84)[,1])
quantile(data.frame(boot.ci.ndf$X37 - boot.ci.ndf$X84)[,1], 0.025)
quantile(data.frame(boot.ci.ndf$X37 - boot.ci.ndf$X84)[,1], 0.975)

{
  ggplot(data = dat, 
         aes(x = Day, y = CP, color = Forage)) + 
  
  geom_point(size = 1.5, 
             show.legend = T,
             position = position_jitter(h = 0.01, w = 0.01),
             alpha = 0.5) +
  
  scale_color_manual(breaks = c("Rye", "Wheat"), 
                     values = c("darkred", "dodgerblue4")) + 
  
  geom_line(data = newDat.CP, 
            aes(x = Day, y = fit, group = Forage), 
            size = 1) +
  
  geom_ribbon(data = subset(newDat.CP, Forage == "Rye"), 
              aes(x = Day, ymin =`2.5 %`, ymax = `97.5 %`),
              fill = "darksalmon", 
              alpha = 0.5, 
              inherit.aes = FALSE) +
  
  geom_ribbon(data = subset(newDat.CP, Forage == "Wheat"), 
              aes(x = Day, ymin = `2.5 %`, ymax = `97.5 %`),
              fill = "lightskyblue1", alpha = 0.5, inherit.aes = FALSE) +
  
  theme_classic() +
    
  labs(x = "Day of grazing period", 
       y = "Crude protein, g 100g\u207B\u00B9 of dry matter forage") +  
  
  scale_y_continuous(breaks = seq(10, 30, 5), 
                     limits = c(9, 30), expand = c(0,0)) +
  
  scale_x_continuous(breaks = seq(0, 46, 2), limits = c(-1, 47), expand = c(0,0)) +
  
  theme(axis.title = element_text(size = 14),
        plot.caption = element_text(size = 11, hjust = 0),   
        axis.text = element_text(size = 11, colour = "black"),
        legend.position = c(.9, .9),
        legend.title = element_blank(),
        legend.direction = "vertical",
        legend.text = element_text(size = 11),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 10, l = 0)))
  }
```

# fat
```{r, message = F}
#model
model = lmer(Fat ~ poly(Day,2)*Forage + (1|Pen) + (1|Paddock/Forage), data = within(dat, Forage <- relevel(Forage, ref = "Rye")))

confint(pairs(emmeans(model, "Forage")))

#diagnostics
plot(model, main = "Residuals vs fitted")
qqnorm(resid(model))
qqline(resid(model))

#regression coefficients 
summary(model, ddf = "Kenward-Roger")
round(confint(model), 2)
anova(model, ddf = "Kenward-Roger")

#random effects
as.data.frame(VarCorr(model))

#R squared
r.squaredGLMM(model)
```

# fat plot
```{r, echo = F}
# Predicted fitted values
newDat.fat = newDat
newDat.fat$fit <- predict.fun(model)

# 95% confidence intervals based on 1000 bootstrap resamples 
newDat.fat <- cbind(newDat.fat, confint(bootMer(model, predict.fun, nsim = 1000, seed = 1), type = "perc"))

min(subset(newDat.fat, Forage == "Rye")$fit)
max(subset(newDat.fat, Forage == "Rye")$fit)
min(subset(newDat.fat, Forage == "Wheat")$fit)
max(subset(newDat.fat, Forage == "Wheat")$fit)

{
  ggplot(data = dat, 
         aes(x = Day, y = Fat, color = Forage)) + 
  
  geom_point(size = 1.5, 
             show.legend = T,
             position = position_jitter(h = 0.01, w = 0.01),
             alpha = 0.5) +
  
  scale_color_manual(breaks = c("Rye", "Wheat"), 
                     values = c("darkred", "dodgerblue4")) + 
  
  geom_line(data = newDat.fat, 
            aes(x = Day, y = fit, group = Forage), 
            size = 1) +
  
  geom_ribbon(data = subset(newDat.fat, Forage == "Rye"), 
              aes(x = Day, ymin =`2.5 %`, ymax = `97.5 %`),
              fill = "darksalmon", 
              alpha = 0.5, 
              inherit.aes = FALSE) +
  
  geom_ribbon(data = subset(newDat.fat, Forage == "Wheat"), 
              aes(x = Day, ymin = `2.5 %`, ymax = `97.5 %`),
              fill = "lightskyblue1", alpha = 0.5, inherit.aes = FALSE) +
  
  theme_classic() +
    
  labs(x = "Day of grazing period", 
       y = "Fat, g 100g\u207B\u00B9 of dry matter forage") +  
  
  scale_y_continuous(breaks = seq(2, 3.5, .25), 
                     limits = c(2, 3.5), expand = c(0,0)) +
  
  scale_x_continuous(breaks = seq(0, 46, 2), limits = c(-1, 47), expand = c(0,0)) +
  
  theme(axis.title = element_text(size = 14),
        plot.caption = element_text(size = 11, hjust = 0),   
        axis.text = element_text(size = 11, colour = "black"),
        legend.position = c(.9, .9),
        legend.title = element_blank(),
        legend.direction = "vertical",
        legend.text = element_text(size = 11),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 10, l = 0)))
  }
```

# NFC
```{r, message = F}
#model
model = lmer(NFC ~ Day*Forage + (1|Pen) + (1|Paddock/Forage), data = within(dat, Forage <- relevel(Forage, ref = "Rye")))

#diagnostics
plot(model, main = "Residuals vs fitted")
qqnorm(resid(model))
qqline(resid(model))

#regression coefficients 
summary(model, ddf = "Kenward-Roger")
round(confint(model), 2)
anova(model, ddf = "Kenward-Roger")

#random effects
as.data.frame(VarCorr(model))

#R squared
r.squaredGLMM(model)
```

# NFC plot
```{r, echo = F}
# Predicted fitted values
newDat.nfc = newDat
newDat.nfc$fit <- predict.fun(model)

# 95% confidence intervals based on 1000 bootstrap resamples 
newDat.nfc <- cbind(newDat.nfc, confint(bootMer(model, predict.fun, nsim = 1000, seed = 1), type = "perc"))

min(subset(newDat.nfc, Forage == "Rye")$fit)
max(subset(newDat.nfc, Forage == "Rye")$fit)
min(subset(newDat.nfc, Forage == "Wheat")$fit)
max(subset(newDat.nfc, Forage == "Wheat")$fit)

{
  ggplot(data = dat, 
         aes(x = Day, y = NFC, color = Forage)) + 
  
  geom_point(size = 1.5, 
             show.legend = T,
             position = position_jitter(h = 0.01, w = 0.01),
             alpha = 0.5) +
  
  scale_color_manual(breaks = c("Rye", "Wheat"), 
                     values = c("darkred", "dodgerblue4")) + 
  
  geom_line(data = newDat.nfc, 
            aes(x = Day, y = fit, group = Forage), 
            size = 1) +
  
  geom_ribbon(data = subset(newDat.nfc, Forage == "Rye"), 
              aes(x = Day, ymin =`2.5 %`, ymax = `97.5 %`),
              fill = "darksalmon", 
              alpha = 0.5, 
              inherit.aes = FALSE) +
  
  geom_ribbon(data = subset(newDat.nfc, Forage == "Wheat"), 
              aes(x = Day, ymin = `2.5 %`, ymax = `97.5 %`),
              fill = "lightskyblue1", alpha = 0.5, inherit.aes = FALSE) +
  
  theme_classic() +
    
  labs(x = "Day of grazing period", 
       y = "NFC, g 100g\u207B\u00B9 of dry matter forage") +  
  
  scale_y_continuous(breaks = seq(15, 40, 5), 
                     limits = c(15, 40), expand = c(0,0)) +
  
  scale_x_continuous(breaks = seq(0, 46, 2), limits = c(-1, 47), expand = c(0,0)) +
  
  theme(axis.title = element_text(size = 14),
        plot.caption = element_text(size = 11, hjust = 0),   
        axis.text = element_text(size = 11, colour = "black"),
        legend.position = c(.9, .9),
        legend.title = element_blank(),
        legend.direction = "vertical",
        legend.text = element_text(size = 11),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 10, l = 0)))
  }
```

# NDF
```{r, message = F}
#model
model = lmer(NDF ~ poly(Day, 2)*Forage + (1|Pen) + (1|Paddock/Forage), control = lmerControl(optimizer = "Nelder_Mead"), data = within(dat, Forage <- relevel(Forage, ref = "Rye")))

#diagnostics
plot(model, main = "Residuals vs fitted")
qqnorm(resid(model))
qqline(resid(model))

#regression coefficients 
summary(model, ddf = "Kenward-Roger")
round(confint(model), 2)
anova(model, ddf = "Kenward-Roger")

#random effects
as.data.frame(VarCorr(model))

#R squared
r.squaredGLMM(model)
```

# NDF plot
```{r, echo = F}
# Predicted fitted values
newDat.ndf = newDat
newDat.ndf$fit <- predict.fun(model)

# 95% confidence intervals based on 1000 bootstrap resamples 
newDat.ndf <- cbind(newDat.ndf, confint(bootMer(model, predict.fun, nsim = 1000, seed = 1), type = "perc"))

boot.ci.ndf <- data.frame(bootMer(model, predict.fun, nsim = 1000, seed = 1)) 

min(subset(newDat.ndf, Forage == "Rye")$fit)
max(subset(newDat.ndf, Forage == "Rye")$fit)
min(subset(newDat.ndf, Forage == "Wheat")$fit)
max(subset(newDat.ndf, Forage == "Wheat")$fit)


#Difference between rye - wheat on d0
mean(data.frame(boot.ci.ndf$X1 - boot.ci.ndf$X48)[,1])
quantile(data.frame(boot.ci.ndf$X1 - boot.ci.ndf$X48)[,1], 0.025)
quantile(data.frame(boot.ci.ndf$X1 - boot.ci.ndf$X48)[,1], 0.975)

#Difference between rye - wheat on d5
mean(data.frame(boot.ci.ndf$X6 - boot.ci.ndf$X53)[,1])
quantile(data.frame(boot.ci.ndf$X6 - boot.ci.ndf$X53)[,1], 0.025)
quantile(data.frame(boot.ci.ndf$X6 - boot.ci.ndf$X53)[,1], 0.975)

#Difference between rye - wheat on d36
mean(data.frame(boot.ci.ndf$X37 - boot.ci.ndf$X84)[,1])
quantile(data.frame(boot.ci.ndf$X37 - boot.ci.ndf$X84)[,1], 0.025)
quantile(data.frame(boot.ci.ndf$X37 - boot.ci.ndf$X84)[,1], 0.975)



{
  ggplot(data = dat, 
         aes(x = Day, y = NDF, color = Forage)) + 
  
  geom_point(size = 1.5, 
             show.legend = T,
             position = position_jitter(h = 0.01, w = 0.01),
             alpha = 0.5) +
  
  scale_color_manual(breaks = c("Rye", "Wheat"), 
                     values = c("darkred", "dodgerblue4")) + 
  
  geom_line(data = newDat.ndf, 
            aes(x = Day, y = fit, group = Forage), 
            size = 1) +
  
  geom_ribbon(data = subset(newDat.ndf, Forage == "Rye"), 
              aes(x = Day, ymin =`2.5 %`, ymax = `97.5 %`),
              fill = "darksalmon", 
              alpha = 0.5, 
              inherit.aes = FALSE) +
  
  geom_ribbon(data = subset(newDat.ndf, Forage == "Wheat"), 
              aes(x = Day, ymin = `2.5 %`, ymax = `97.5 %`),
              fill = "lightskyblue1", alpha = 0.5, inherit.aes = FALSE) +
  
  theme_classic() +
    
  labs(x = "Day of grazing period", 
       y = "NDF, g 100g\u207B\u00B9 of dry matter forage") +  
  
  scale_y_continuous(breaks = seq(30, 60, 5), 
                     limits = c(30, 60), expand = c(0,0)) +
  
  scale_x_continuous(breaks = seq(0, 46, 2), limits = c(-1, 47), expand = c(0,0)) +
  
  theme(axis.title = element_text(size = 14),
        plot.caption = element_text(size = 11, hjust = 0),   
        axis.text = element_text(size = 11, colour = "black"),
        legend.position = c(.1, .9),
        legend.title = element_blank(),
        legend.direction = "vertical",
        legend.text = element_text(size = 11),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 10, l = 0)))
  }
```

# TTNDFD
```{r, message = F}
#model
model = lmer(TTNDFD ~ poly(Day,2)*Forage + (1|Pen) + (1|Paddock/Forage), control = lmerControl(optimizer = "Nelder_Mead"), data = within(dat, Forage <- relevel(Forage, ref = "Rye")))

#diagnostics
plot(model, main = "Residuals vs fitted")
qqnorm(resid(model))
qqline(resid(model))

#regression coefficients 
summary(model, ddf = "Kenward-Roger")
round(confint(model), 2)
anova(model, ddf = "Kenward-Roger")

#random effects
as.data.frame(VarCorr(model))

#R squared
r.squaredGLMM(model)
```

# TTNDFD plot
```{r, echo = F}
# Predicted fitted values
newDat.ttndfd = newDat
newDat.ttndfd$fit <- predict.fun(model)

# 95% confidence intervals based on 1000 bootstrap resamples 
newDat.ttndfd <- cbind(newDat.ttndfd, confint(bootMer(model, predict.fun, nsim = 1000, seed = 1), type = "perc"))

min(subset(newDat.ttndfd, Forage == "Rye")$fit)
max(subset(newDat.ttndfd, Forage == "Rye")$fit)
min(subset(newDat.ttndfd, Forage == "Wheat")$fit)
max(subset(newDat.ttndfd, Forage == "Wheat")$fit)

boot.ci.ttndfd <- data.frame(bootMer(model, predict.fun, nsim = 1000, seed = 1)) 

mean(subset(newDat.ttndfd, Day == "46")$fit)

#Difference between rye - wheat on d0
mean(data.frame(boot.ci.ndf$X1 - boot.ci.ndf$X48)[,1])
quantile(data.frame(boot.ci.ndf$X1 - boot.ci.ndf$X48)[,1], 0.025)
quantile(data.frame(boot.ci.ndf$X1 - boot.ci.ndf$X48)[,1], 0.975)

#Difference between rye - wheat on d5
mean(data.frame(boot.ci.ndf$X6 - boot.ci.ndf$X53)[,1])
quantile(data.frame(boot.ci.ndf$X6 - boot.ci.ndf$X53)[,1], 0.025)
quantile(data.frame(boot.ci.ndf$X6 - boot.ci.ndf$X53)[,1], 0.975)

#Difference between rye - wheat on d36
mean(data.frame(boot.ci.ndf$X37 - boot.ci.ndf$X84)[,1])
quantile(data.frame(boot.ci.ndf$X37 - boot.ci.ndf$X84)[,1], 0.025)
quantile(data.frame(boot.ci.ndf$X37 - boot.ci.ndf$X84)[,1], 0.975)


{
  ggplot(data = dat, 
         aes(x = Day, y = TTNDFD, color = Forage)) + 
  
  geom_point(size = 1.5, 
             show.legend = T,
             position = position_jitter(h = 0.01, w = 0.01),
             alpha = 0.5) +
  
  scale_color_manual(breaks = c("Rye", "Wheat"), 
                     values = c("darkred", "dodgerblue4")) + 
  
  geom_line(data = newDat.ttndfd, 
            aes(x = Day, y = fit, group = Forage), 
            size = 1) +
  
  geom_ribbon(data = subset(newDat.ttndfd, Forage == "Rye"), 
              aes(x = Day, ymin =`2.5 %`, ymax = `97.5 %`),
              fill = "darksalmon", 
              alpha = 0.5, 
              inherit.aes = FALSE) +
  
  geom_ribbon(data = subset(newDat.ttndfd, Forage == "Wheat"), 
              aes(x = Day, ymin = `2.5 %`, ymax = `97.5 %`),
              fill = "lightskyblue1", alpha = 0.5, inherit.aes = FALSE) +
  
  theme_classic() +
    
  labs(x = "Day of grazing period", 
       y = "TTNDFD, g 100g\u207B\u00B9 of NDF") +  
  
  scale_y_continuous(breaks = seq(30, 75, 5), 
                     limits = c(30, 75), expand = c(0,0)) +
  
  scale_x_continuous(breaks = seq(0, 46, 2), limits = c(-1, 47), expand = c(0,0)) +
  
  theme(axis.title = element_text(size = 14),
        plot.caption = element_text(size = 11, hjust = 0),   
        axis.text = element_text(size = 11, colour = "black"),
        legend.position = c(.9, .9),
        legend.title = element_blank(),
        legend.direction = "vertical",
        legend.text = element_text(size = 11),
        axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
        axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 10, l = 0)))
  }
```

